### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by raulbochka** [carlosedubarreto/vibe_win_install#17]
when i run python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display i get RuntimeError: CUDA error: no kernel image is available for execution on the device 
im using a gt 710 gpu

**Comment by carlosedubarreto** [comment]
can you show the installation log? (just copy what is on the screen after running the bat file?)

Maybe there was some error.

Just run the bat again (on the enviroment you´ve created,) and send here the text.

**Comment by raulbochka** [comment]
here s the whole thing 

(base) C:\Users\HP>conda activate venv_vibe

(venv_vibe) C:\Users\HP>conda install cudatoolkit=10.1 cudnn=7.6.0
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


(venv_vibe) C:\Users\HP>cd mocap

(venv_vibe) C:\Users\HP\mocap>cd vibe

(venv_vibe) C:\Users\HP\mocap\vibe>conda install cudatoolkit=10.1 cudnn=7.6.0
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


(venv_vibe) C:\Users\HP\mocap\vibe>install_conda.bat

(venv_vibe) C:\Users\HP\mocap\vibe>pip install mkl intel-openmp
Requirement already satisfied: mkl in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (2021.3.0)
Requirement already satisfied: intel-openmp in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (2021.3.0)
Requirement already satisfied: tbb==2021.* in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from mkl) (2021.3.0)

(venv_vibe) C:\Users\HP\mocap\vibe>pip install torch==1.4.0 torchvision==0.5.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Requirement already satisfied: torch==1.4.0 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (1.4.0+cu92)
Requirement already satisfied: torchvision==0.5.0 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (0.5.0+cu92)
Requirement already satisfied: six in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from torchvision==0.5.0) (1.16.0)
Requirement already satisfied: numpy in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from torchvision==0.5.0) (1.17.5)
Requirement already satisfied: pillow>=4.1.1 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from torchvision==0.5.0) (7.1.0)

(venv_vibe) C:\Users\HP\mocap\vibe>pip install numpy==1.17.5
Requirement already satisfied: numpy==1.17.5 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (1.17.5)

(venv_vibe) C:\Users\HP\mocap\vibe>pip install git+https://github.com/giacaglia/pytube.git --upgrade
Collecting git+https://github.com/giacaglia/pytube.git
  Cloning https://github.com/giacaglia/pytube.git to c:\users\hp\appdata\local\temp\pip-req-build-z5_srbe3
  Running command git clone -q https://github.com/giacaglia/pytube.git 'C:\Users\HP\AppData\Local\Temp\pip-req-build-z5_srbe3'

(venv_vibe) C:\Users\HP\mocap\vibe>pip install -r requirements_alter.txt
Collecting git+https://github.com/mattloper/chumpy.git (from -r requirements_alter.txt (line 23))
  Cloning https://github.com/mattloper/chumpy.git to c:\users\hp\appdata\local\temp\pip-req-build-9vkvtwcz
  Running command git clone -q https://github.com/mattloper/chumpy.git 'C:\Users\HP\AppData\Local\Temp\pip-req-build-9vkvtwcz'
Collecting git+https://github.com/mkocabas/yolov3-pytorch.git (from -r requirements_alter.txt (line 24))
  Cloning https://github.com/mkocabas/yolov3-pytorch.git to c:\users\hp\appdata\local\temp\pip-req-build-gq_51cp1
  Running command git clone -q https://github.com/mkocabas/yolov3-pytorch.git 'C:\Users\HP\AppData\Local\Temp\pip-req-build-gq_51cp1'
Collecting git+https://github.com/mkocabas/multi-person-tracker.git (from -r requirements_alter.txt (line 25))
  Cloning https://github.com/mkocabas/multi-person-tracker.git to c:\users\hp\appdata\local\temp\pip-req-build-sdtr7i42
  Running command git clone -q https://github.com/mkocabas/multi-person-tracker.git 'C:\Users\HP\AppData\Local\Temp\pip-req-build-sdtr7i42'
Requirement already satisfied: tqdm==4.28.1 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 1)) (4.28.1)
Requirement already satisfied: yacs==0.1.6 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 2)) (0.1.6)
Requirement already satisfied: h5py==2.10.0 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 3)) (2.10.0)
Requirement already satisfied: numpy==1.17.5 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 4)) (1.17.5)
Requirement already satisfied: scipy==1.4.1 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 5)) (1.4.1)
Requirement already satisfied: numba==0.47.0 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 6)) (0.47.0)
Requirement already satisfied: smplx==0.1.26 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 7)) (0.1.26)
Requirement already satisfied: gdown==3.6.4 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 8)) (3.6.4)
Requirement already satisfied: PyYAML==5.3.1 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 9)) (5.3.1)
Requirement already satisfied: joblib==0.14.1 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 10)) (0.14.1)
Requirement already satisfied: pillow==7.1.0 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 11)) (7.1.0)
Requirement already satisfied: trimesh==3.5.25 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 12)) (3.5.25)
Requirement already satisfied: pyrender==0.1.36 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 13)) (0.1.36)
Requirement already satisfied: progress==1.5 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 14)) (1.5)
Requirement already satisfied: filterpy==1.4.5 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 15)) (1.4.5)
Requirement already satisfied: matplotlib==3.1.3 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 16)) (3.1.3)
Requirement already satisfied: tensorflow==1.15.4 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 17)) (1.15.4)
Requirement already satisfied: torchvision==0.5.0 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 18)) (0.5.0+cu92)
Requirement already satisfied: scikit-image==0.16.2 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 19)) (0.16.2)
Requirement already satisfied: scikit-video==1.1.11 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 20)) (1.1.11)
Requirement already satisfied: opencv-python==4.1.2.30 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 21)) (4.1.2.30)
Requirement already satisfied: llvmlite==0.32.1 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 22)) (0.32.1)
Requirement already satisfied: six>=1.11.0 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from chumpy==0.70->-r requirements_alter.txt (line 23)) (1.16.0)
Requirement already satisfied: setuptools in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from numba==0.47.0->-r requirements_alter.txt (line 6)) (52.0.0.post20210125)
Requirement already satisfied: torchgeometry>=0.1.2 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from smplx==0.1.26->-r requirements_alter.txt (line 7)) (0.1.2)
Requirement already satisfied: torch>=1.0.1.post2 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from smplx==0.1.26->-r requirements_alter.txt (line 7)) (1.4.0+cu92)
Requirement already satisfied: requests in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from gdown==3.6.4->-r requirements_alter.txt (line 8)) (2.26.0)
Requirement already satisfied: PyOpenGL==3.1.0 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from pyrender==0.1.36->-r requirements_alter.txt (line 13)) (3.1.0)
Requirement already satisfied: pyglet>=1.4.10 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from pyrender==0.1.36->-r requirements_alter.txt (line 13)) (1.5.18)
Requirement already satisfied: imageio in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from pyrender==0.1.36->-r requirements_alter.txt (line 13)) (2.9.0)
Requirement already satisfied: freetype-py in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from pyrender==0.1.36->-r requirements_alter.txt (line 13)) (2.2.0)
Requirement already satisfied: networkx in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from pyrender==0.1.36->-r requirements_alter.txt (line 13)) (2.6.2)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from matplotlib==3.1.3->-r requirements_alter.txt (line 16)) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from matplotlib==3.1.3->-r requirements_alter.txt (line 16)) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from matplotlib==3.1.3->-r requirements_alter.txt (line 16)) (1.3.1)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from matplotlib==3.1.3->-r requirements_alter.txt (line 16)) (2.8.2)
Requirement already satisfied: absl-py>=0.7.0 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (0.13.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (1.1.0)
Requirement already satisfied: grpcio>=1.8.6 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (1.39.0)
Requirement already satisfied: keras-applications>=1.0.8 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (1.0.8)
Requirement already satisfied: tensorflow-estimator==1.15.1 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (1.15.1)
Requirement already satisfied: astor>=0.6.0 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (0.8.1)
Requirement already satisfied: wheel>=0.26 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (0.36.2)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (3.3.0)
Requirement already satisfied: protobuf>=3.6.1 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (3.17.3)
Requirement already satisfied: gast==0.2.2 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (0.2.2)
Requirement already satisfied: keras-preprocessing>=1.0.5 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (1.1.2)
Requirement already satisfied: tensorboard<1.16.0,>=1.15.0 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (1.15.0)
Requirement already satisfied: google-pasta>=0.1.6 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (0.2.0)
Requirement already satisfied: wrapt>=1.11.1 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (1.12.1)
Requirement already satisfied: PyWavelets>=0.4.0 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from scikit-image==0.16.2->-r requirements_alter.txt (line 19)) (1.1.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (3.3.4)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (2.0.1)
Requirement already satisfied: importlib-metadata in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from markdown>=2.6.8->tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (4.6.1)
Requirement already satisfied: typing-extensions>=3.6.4 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (3.10.0.0)
Requirement already satisfied: zipp>=0.5 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (3.5.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from requests->gdown==3.6.4->-r requirements_alter.txt (line 8)) (2.0.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from requests->gdown==3.6.4->-r requirements_alter.txt (line 8)) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from requests->gdown==3.6.4->-r requirements_alter.txt (line 8)) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\miniconda3\envs\venv_vibe\lib\site-packages (from requests->gdown==3.6.4->-r requirements_alter.txt (line 8)) (2021.5.30)

(venv_vibe) C:\Users\HP\mocap\vibe>prepare_data.bat

(venv_vibe) C:\Users\HP\mocap\vibe>md data
Un sous-répertoire ou un fichier data existe déjà.

(venv_vibe) C:\Users\HP\mocap\vibe>cd data

(venv_vibe) C:\Users\HP\mocap\vibe\data>gdown "https://drive.google.com/uc?id=1untXhYOLQtpNEy4GTY_0fL_H-k6cTf_r"
Downloading...
From: https://drive.google.com/uc?id=1untXhYOLQtpNEy4GTY_0fL_H-k6cTf_r
To: C:\Users\HP\mocap\vibe\data\vibe_data.zip
561MB [07:23, 1.31MB/s]

(venv_vibe) C:\Users\HP\mocap\vibe\data>cd ..

(venv_vibe) C:\Users\HP\mocap\vibe>echo #### Extract the files from vibe_data ###
#### Extract the files from vibe_data ###

(venv_vibe) C:\Users\HP\mocap\vibe>python unzip_vibe_data.py

(venv_vibe) C:\Users\HP\mocap\vibe>copy data\vibe_data\sample_video.mp4 .
        1 fichier(s) copié(s).

(venv_vibe) C:\Users\HP\mocap\vibe>echo ### creating place for torch model ###
### creating place for torch model ###

(venv_vibe) C:\Users\HP\mocap\vibe>md \Users\HP\.torch\models
Un sous-répertoire ou un fichier \Users\HP\.torch\models existe déjà.

(venv_vibe) C:\Users\HP\mocap\vibe>copy data\vibe_data\yolov3.weights \Users\HP\.torch\models
        1 fichier(s) copié(s).

(venv_vibe) C:\Users\HP\mocap\vibe>echo ### creating place for yolo config ###
### creating place for yolo config ###

(venv_vibe) C:\Users\HP\mocap\vibe>md \Users\HP\.torch\config
Un sous-répertoire ou un fichier \Users\HP\.torch\config existe déjà.

(venv_vibe) C:\Users\HP\mocap\vibe>copy yolov3.cfg \Users\HP\.torch\config
        1 fichier(s) copié(s).

(venv_vibe) C:\Users\HP\mocap\vibe>python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp\sample_video_mp4/%06d.png"
Images saved to "/tmp\sample_video_mp4"
Input video number of frames 300
Running Multi-Person-Tracker
  0%|                                                                                          | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo_alter.py", line 405, in <module>
    main(args)
  File "demo_alter.py", line 95, in main
    tracking_results = mot(image_folder)
  File "C:\Users\HP\miniconda3\envs\venv_vibe\lib\site-packages\multi_person_tracker\mpt.py", line 284, in __call__
    trackers = self.run_tracker(dataloader)
  File "C:\Users\HP\miniconda3\envs\venv_vibe\lib\site-packages\torch\autograd\grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "C:\Users\HP\miniconda3\envs\venv_vibe\lib\site-packages\multi_person_tracker\mpt.py", line 78, in run_tracker
    predictions = self.detector(batch)
  File "C:\Users\HP\miniconda3\envs\venv_vibe\lib\site-packages\torch\autograd\grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "C:\Users\HP\miniconda3\envs\venv_vibe\lib\site-packages\yolov3\yolo.py", line 61, in __call__
    img, _ = pad_to_square(img, 0)
  File "C:\Users\HP\miniconda3\envs\venv_vibe\lib\site-packages\yolov3\utils\datasets.py", line 23, in pad_to_square
    img = F.pad(img, pad, "constant", value=pad_value)
  File "C:\Users\HP\miniconda3\envs\venv_vibe\lib\site-packages\torch\nn\functional.py", line 2862, in pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA error: no kernel image is available for execution on the device

(venv_vibe) C:\Users\HP\mocap\vibe>

**Comment by carlosedubarreto** [comment]
interesting, looks that the installation ran smooth...

Did you try to update the driver?
Do your card has CUDA 10 support?

**Comment by raulbochka** [comment]
i have a gt 710 and honestly i dont know what to do if it has or if it has not

**Comment by carlosedubarreto** [comment]
and I dont know what to suggest you to do to make it work.

But I can ask, what do you wantes to do with the result from vibe?
I may have another option to you that might work

**Comment by carlosedubarreto** [comment]
The suggestion i was going to make is to use mediapipe inside of blender.

Here it is a link showing the process that you can do to retarget the animation to a custom character

https://www.patreon.com/posts/dev-preview-and-53711794

**Comment by raulbochka** [comment]
for the media pipe instal should i do it in cmd or where it s really unclear

**Comment by carlosedubarreto** [comment]
you do it in CMD.

**Comment by raulbochka** [comment]
![Capture d’écran 2021-08-13 141422](https://user-images.githubusercontent.com/87949953/129355702-4d07c2e8-188e-49c4-81ed-880675ab43b8.png)
okqy i get this

**Comment by carlosedubarreto** [comment]
looks like you are missing double quotes.
Probably if you run this instructioins bollow, it might works (i tried to get the path that was on the screenshot)

To install mediapipe
"c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.exe" "c:\Program Files\Blender Foundation\Blender 2.93\python\lib\site-packages\pip install mediapipe"

To install opencv
"c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.exe" "c:\Program Files\Blender Foundation\Blender 2.93\python\lib\site-packages\pip install opencv-python"

**Comment by raulbochka** [comment]
![cmdd](https://user-images.githubusercontent.com/87949953/129380934-f88c6e12-21ed-40cf-af24-060146bc575f.png)
is this what how it should look

**Comment by carlosedubarreto** [comment]
i think you are executing one at a time, and you should run both commands together.

like this
this command you should paste in CMD as one line
`"c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.exe" "c:\Program Files\Blender Foundation\Blender 2.93\python\lib\site-packages\pip install mediapipe"`


and this other is also in one line
`"c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.exe" "c:\Program Files\Blender Foundation\Blender 2.93\python\lib\site-packages\pip install opencv-python"`

**Comment by raulbochka** [comment]
okay but i guess i have the wrong path can u please show what inside the folder of that path so i can search for it

**Comment by carlosedubarreto** [comment]
the first folder would be something like this
![image](https://user-images.githubusercontent.com/4061130/129393167-c426c2d7-b0c5-44ad-8ecf-62477bc924d2.png)


the second folder should be something like this
![image](https://user-images.githubusercontent.com/4061130/129393767-0a93cd2d-a684-404b-b1d1-4f63c5ca3c5b.png)

**Comment by raulbochka** [comment]
[Errno 2] No such file or directory  still happen

**Comment by carlosedubarreto** [comment]
can you look at the properties of the shortcut to see the path of your blender?

like this
![image](https://user-images.githubusercontent.com/4061130/129422129-e5885665-64c0-419b-88a6-cf58d40e853e.png)

**Comment by raulbochka** [comment]
![Capture d’écran 2021-07-05 211123](https://user-images.githubusercontent.com/87949953/129426338-353dbb27-1ab5-4378-90ac-0e0530dea162.png)

**Comment by raulbochka** [comment]
![Capture d’écran 2021-08-14 011403](https://user-images.githubusercontent.com/87949953/129426352-7e342919-63ed-44df-9418-25a624630877.png)

**Comment by carlosedubarreto** [comment]
Sorry, now i noticed, the path was really wrong (on the last part of the path.) 😅

Try this one

Mediapipe
"c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.exe" "c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pip install mediapipe"

OpenCV
"c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.exe" "c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pip install opencv-python"

**Comment by carlosedubarreto** [comment]
if you still have trouble, you could try this script I've done.
There is a video showing how to do

https://www.patreon.com/posts/54890147

**Comment by raulbochka** [comment]
i tried cmd with the new code line same error and tried your new methode still nothing 
![Capture d’écran 2021-08-14 190104](https://user-images.githubusercontent.com/87949953/129454846-9be4f11d-557b-4a13-b6bc-4a9586a41bdc.png)

**Comment by carlosedubarreto** [comment]
That´s harder than I thought 😅

Can you send what shows up on the console?
![image](https://user-images.githubusercontent.com/4061130/129459683-6b27ff46-1255-428f-a542-96741401dffc.png)


Another thing... looks like yu are running blender form the program files...
that folder is protected... Probably thats the problem.

I gues you will have to start blender as Administrator, to be able to install opencv and mediapipe...

Please try this first.

Open blender as administrator (right click the shortcut and choose run as administrator) 
then run the script again.

If it doesnt work, please send me what shows in the console

**Comment by raulbochka** [comment]
![toggle](https://user-images.githubusercontent.com/87949953/129467997-10bd59df-2126-4906-9a98-076ebafbe0fe.png)

**Comment by carlosedubarreto** [comment]
Oh my 😥it was intalled on you windows python installation 🙄

One thing I know that works, is.

You can copy those folders and files manually

Folder files to copy from :
`c:\users\hp\appdata\roaming\python\python39\site_packages`

FOLDER:
```
absl
attr
cv2
dateutil
google
matplotlib
mediapipe
PIL
wheel
```

FILES:
```
cycler.py
kiwisolver.cp39-win_amd64.pyd (probably thats the name in your machine)
pyparsing.py
six.py
```


paste them into:
`c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages`


an example of the folders and files that you will have to copy, this example is from my pc that has the python 3.7 installed, so at least the kiwi file will be different from what you will see in your pc.

![image](https://user-images.githubusercontent.com/4061130/129472318-e4bee547-bef0-45d5-9ace-0753c453a928.png)


I think will work, i hope 😃

**Comment by raulbochka** [comment]
you forgot mpl toolkits so yeah the command got excuted but when i try to load a vide it says location unkown i tried more than one in diffrent folders any solution

**Comment by carlosedubarreto** [comment]
Thats odd, I never had such error... And I listed all the packs that were shown on your screen, and considering the ones that showed to me when I ran the installation of those python packs in my pc 🤔
can you show the screen? If might have more information that could help.

**Comment by carlosedubarreto** [comment]
Think I found it.

Looks like you have to copy also this folder and this file
![image](https://user-images.githubusercontent.com/4061130/129545717-f731a8be-9b10-450a-885a-76a17641d201.png)

**Comment by raulbochka** [comment]
even after doing this i get still get it 
![Capture d’écran 2021-08-16 205525](https://user-images.githubusercontent.com/87949953/129615452-15e73f29-87cd-4602-90c8-41d295eaa05d.png)
![Capture d’écran 2021-08-16 205550](https://user-images.githubusercontent.com/87949953/129615462-f162c0b0-4cbf-46ca-8d33-165cc4bfe5d8.png)

**Comment by carlosedubarreto** [comment]
thats so wierd.
Can you get a portable blender file?
Thats what I use and have no problem with installations.

https://www.blender.org/download/Blender2.93/blender-2.93.2-windows-x64.zip/

and unzip it in a folder like c:\Blender

and try the script again (if you are not yet tired of trying 😅)

**Comment by raulbochka** [comment]
that is the blender i am using i guess it s just not going to work for me thank you for being patient and for the technical support sir

**Comment by carlosedubarreto** [comment]
I mean to use the zip option, even the same version.

The reason is, when you use the installation option of blender. The file goes to the program files folder, and that folder is protected by the system. So its one more level of problem that you can have to do things that are not automated in blender.


So using the zip file version, you can have more flexibility.
I for example, dont use installed versions since 2.79, because using zip I can choose at anytime the version of blender that I want to use. Sometimes, one version allow to use some options and other versions allows to use other.

another example is cycles x.

I do my stuff in 2.93, but when I need to render, I open the cycles-x alpha to render my scenes, because of its blazing fast speed.

So, if you still want to try this mediapipe solution to get animation from video, you could do this one last test. 😃

**Comment by raulbochka** [comment]
okay should i recopy all the folders in the zip file too?

**Comment by carlosedubarreto** [comment]
maybe you dont need to do that if you are using the same version....

At first, just unzip the blender to a folder and test it.

**Comment by carlosedubarreto** [comment]
Sorry, you will have to copy them again. I was confused, I forgot that mediapipe is a python package and not an addon

**Comment by raulbochka** [comment]
i ve been trying stuff here and there and i found <open mmd> and i have running the only problem i have is retargeting i m using a metahuman rokoko does not get the job done i think you would like open mmd
![Capture d’écran 2021-08-18 075749](https://user-images.githubusercontent.com/87949953/129845433-80c71d00-b348-4758-a27f-3859eb80e71f.png)

**Comment by carlosedubarreto** [comment]
OpenMMD I didnt know it....
I'll take a look, thanks...

But wait... you were able to use mediapipe? Did you make it run?

**Comment by raulbochka** [comment]
no unfortunately

**Comment by carlosedubarreto** [comment]
Sorry I ran out of ideas. 😥
If you want to try we could try to schedule a time for a remote desktop session. 
If you liked the iode, we could talk via twitter to arrange things.
You can find me at 
https://twitter.com/carlosedubarret

**Comment by raulbochka** [comment]
yes please
