### ISSUE TITLE
CPU without GPU

### ISSUE THREAD

**Issue by zhangchengzhi-max** [carlosedubarreto/vibe_win_install#19]
The last step is this error. My computer has no GPU. According to this prompt, I don't know where to change the code. Please help. Thank you
![image](https://user-images.githubusercontent.com/63695075/132863565-4868ff14-1d2c-4286-8061-ac231edd3270.png)

**Comment by carlosedubarreto** [comment]
Hello.
I cant really do much.
Probably there is an issue on the original github page talking about it.

for example this link brings lots of answers about this question

https://github.com/mkocabas/VIBE/issues?q=is%3Aissue+cpu+

**Comment by zhangchengzhi-max** [comment]
I have successfully run the code. Anyway, thank you for the Windows version of vibe tutorial!
