### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by andreshev** [carlosedubarreto/vibe_win_install#2]
(venv_vibe) F:\Python\vibe>python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp\sample_video_mp4/%06d.png"
Images saved to "/tmp\sample_video_mp4"
Input video number of frames 301
Downloading files from https://pjreddie.com/media/files/yolov3.weights
Traceback (most recent call last):
  File "demo_alter.py", line 405, in <module>
    main(args)
  File "demo_alter.py", line 93, in main
    yolo_img_size=args.yolo_img_size,
  File "D:\Users\Webwork\miniconda3\envs\venv_vibe\lib\site-packages\multi_person_tracker\mpt.py", line 53, in __init__
    device=self.device, img_size=yolo_img_size, person_detector=True, video=True, return_dict=True
  File "D:\Users\Webwork\miniconda3\envs\venv_vibe\lib\site-packages\yolov3\yolo.py", line 32, in __init__
    download_url(url, outdir)
  File "D:\Users\Webwork\miniconda3\envs\venv_vibe\lib\site-packages\yolov3\yolo.py", line 11, in download_url
    subprocess.call(cmd)
  File "D:\Users\Webwork\miniconda3\envs\venv_vibe\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Users\Webwork\miniconda3\envs\venv_vibe\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\Users\Webwork\miniconda3\envs\venv_vibe\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**ffmpeg** is installed and running, creates a folder "F:\tmp\sample_video_mp4" and places a sequence of images (png 1920x1080) there.
I'm using miniconda on windows 10., python3.8 I Installed all libraries successfully without error accord to your instruction.

**Comment by carlosedubarreto** [comment]
Hello @andreshev 

I think the first issue posted here can help you.
Take a look at it please and see if it helps

https://github.com/carlosedubarreto/vibe_win_install/issues/1

**Comment by andreshev** [comment]
Ok thank you, it helped for me. Can you explain next: "copy the 2.82 folder to the same folder that you have the python installation used"
I need put the contents of the "2.82" folder in the python root directory or the folder  "2.82" 

>>> import sys
>>> print(sys.executable)
D:\Users\Webwork\miniconda3\envs\venv_vibe\python.exe

**Comment by carlosedubarreto** [comment]
Sure.
from the folder you posted, I guess you should copy the  bledner 2.82 folder to this folder

D:\Users\Webwork\miniconda3\envs\venv_vibe\

look at my pc.
this folder has the python (on the venv_vib virtual enviroment)
![image](https://user-images.githubusercontent.com/4061130/104121919-a5c2d480-5320-11eb-8052-607f6e92c100.png)

So I pasted the blender 2.82 folder in it.
![image](https://user-images.githubusercontent.com/4061130/104121927-b70be100-5320-11eb-9613-7eb21705782a.png)

copying from the blender zip file, the 2.82 folder will have these folders
![image](https://user-images.githubusercontent.com/4061130/104121934-cc810b00-5320-11eb-9c2e-b1d455e0e5cc.png)

**Comment by andreshev** [comment]
Ok thank you, I have already decided. Want to add: 
>>> import sys
>>> print(sys.executable)

**Comment by carlosedubarreto** [comment]
LOL, sorry, now that I read again was that I understood the real question....
But I guess you managed to find the way to do it.

Is it working?

**Comment by andreshev** [comment]
yes, great work

**Comment by carlosedubarreto** [comment]
Thanks for the feedback.
I'm closing this issue
