### ISSUE TITLE
error when import bpy

### ISSUE THREAD

**Issue by xuguozhi** [carlosedubarreto/vibe_win_install#24]
bpy: couldn't find 'scripts/modules', blender probably wont start.
Freestyle: couldn't find 'scripts/freestyle/modules', Freestyle won't work properly.
ModuleNotFoundError: No module named 'bpy_types'
ModuleNotFoundError: No module named 'bpy_types'

**Comment by carlosedubarreto** [comment]
I guess probably you are trying to import the animation in blender right?
probably it would be easier to use the import mocap addon I did.
It makes easier to get those animations inside of blender and you can have it for free.
https://carlosedubarreto.gumroad.com/l/mocap_import

**Comment by xuguozhi** [comment]
> I guess probably you are trying to import the animation in blender right? probably it would be easier to use the import mocap addon I did. It makes easier to get those animations inside of blender and you can have it for free. https://carlosedubarreto.gumroad.com/l/mocap_import

I also find NV audio2face Blender addon, great!
