### ISSUE TITLE
.fbx conversion error

### ISSUE THREAD

**Issue by alivemachine** [carlosedubarreto/vibe_win_install#3]
It seems that the **.fbx conversion** does not work in many situations.
The sample video conversion to fbx worked but any other video gave me the following error:

`Traceback (most recent call last):
  File "lib/utils/fbx_output.py", line 320, in <module>
    person_id=args.person_id
  File "lib/utils/fbx_output.py", line 166, in process_poses
    poses = data[person_id]['pose']
KeyError: 1
Error: Not freed memory blocks: 8, total unfreed memory 0.010223 MB`

It seems to be linked to having multiple people in the shots? Or to having people disappear/reappear?

**Comment by carlosedubarreto** [comment]
That´s odd... I've never seen this issue. Neither have an idea why it would work only with the provided sample file.

can you send the command you used to do the fbx conversion?

**Comment by alivemachine** [comment]
So far I'm using the one you provided in the win_install readme:
```
(venv_vibe) D:\MOCAP\VIBE>python lib/utils/fbx_output.py --input output/sample_video/vibe_output.pkl --output output/sample_video/fbx_output.fbx --fps_source 30 --fps_target 30 --gender female
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
Input path: D:\MOCAP\VIBE\output/sample_video/vibe_output.pkl
Output path: D:\MOCAP\VIBE\output/sample_video/fbx_output.fbx
Processing: D:\MOCAP\VIBE\output/sample_video/vibe_output.pkl
Traceback (most recent call last):
  File "lib/utils/fbx_output.py", line 320, in <module>
    person_id=args.person_id
  File "lib/utils/fbx_output.py", line 166, in process_poses
    poses = data[person_id]['pose']
KeyError: 1
Error: Not freed memory blocks: 8, total unfreed memory 0.010223 MB
```
I'm only switching file names

**Comment by alivemachine** [comment]
Here is a file that will convert: [drive.google.com/file/d/137Ndwf9PtsbW5GGAPRxiiVUg9HUUBMR8](https://drive.google.com/file/d/137Ndwf9PtsbW5GGAPRxiiVUg9HUUBMR8/view?usp=sharing)
Here is a file that won't convert: [drive.google.com/file/d/1AsekACWqJ8Vr57y9eOCa-B4jtG0au8Rj](https://drive.google.com/file/d/1AsekACWqJ8Vr57y9eOCa-B4jtG0au8Rj/view?usp=sharing)

They both have been computed from the colab notebook and downloaded for local conversion

**Comment by carlosedubarreto** [comment]
I tested and had the same problem
![image](https://user-images.githubusercontent.com/4061130/104899210-53ee0000-5959-11eb-9f29-81422ee9ccb7.png)

**Comment by alivemachine** [comment]
Absolutely, here is the source file: 
https://drive.google.com/file/d/1XY7X6gCvZRXy6NbKb9E1Ak6IkO-pgc5s/view?usp=sharing
Thank you for trying!

**Comment by carlosedubarreto** [comment]
Sorry for the late reponse.
I tryied to test the vibe conversion, but my installation stopped working, and I dont know why.
As I'm not using VIBE anymore (because I'm testing another solution that seems better for my needs) I wont be able to test it unfortunately

**Comment by carlosedubarreto** [comment]
@alivemachine , I think I found the problem.
The video used has a lot of people, so when you run the original code withouit using a person id, it gives error, probably because there are not enought information to convert that person to FBX.

I testes with person id 3 and worked.

The command was like this

`python lib/utils/fbx_output.py --input output/NBA_footage/vibe_output.pkl --output output/NBA_footage/fbx_output.fbx --fps_source 30 --fps_target 30 --gender male --person_id 3`

the resulting fbx imported in blender of this person id 3

https://user-images.githubusercontent.com/4061130/112769219-3c389500-8ff6-11eb-9769-0ef92a650b0c.mp4
