### ISSUE TITLE
I am getting this error

### ISSUE THREAD

**Issue by moustafaahmed365** [carlosedubarreto/vibe_win_install#6]
(base) C:\Users\moust>cd\

(base) C:\>cd MOCAP1

(base) C:\MOCAP1>cd VIBE

(base) C:\MOCAP1\VIBE>conda create -n venv_vibe python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\moust\miniconda3\envs\venv_vibe

  added / updated specs:
    - python=3.7

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2021.1.19-haa95532_0
  certifi            pkgs/main/win-64::certifi-2020.12.5-py37haa95532_0
  openssl            pkgs/main/win-64::openssl-1.1.1i-h2bbff1b_0
  pip                pkgs/main/win-64::pip-20.3.3-py37haa95532_0
  python             pkgs/main/win-64::python-3.7.9-h60c2a47_0
  setuptools         pkgs/main/win-64::setuptools-52.0.0-py37haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.33.0-h2a8f88b_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37_0
  zlib               pkgs/main/win-64::zlib-1.2.11-h62dcd97_4

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate venv_vibe
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) C:\MOCAP1\VIBE>conda activate venv_vibe

(venv_vibe) C:\MOCAP1\VIBE>conda install cudatoolkit=10.1 cudnn=7.6.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\moust\miniconda3\envs\venv_vibe

  added / updated specs:
    - cudatoolkit=10.1
    - cudnn=7.6.0

The following NEW packages will be INSTALLED:

  cudatoolkit        pkgs/main/win-64::cudatoolkit-10.1.243-h74a9793_0
  cudnn              pkgs/main/win-64::cudnn-7.6.0-cuda10.1_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(venv_vibe) C:\MOCAP1\VIBE>install_conda.bat

(venv_vibe) C:\MOCAP1\VIBE>pip install mkl intel-openmp
Collecting intel-openmp
  Downloading intel_openmp-2021.1.2-py2.py3-none-win_amd64.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.2 MB/s
Collecting mkl
  Downloading mkl-2021.1.1-py2.py3-none-win_amd64.whl (228.8 MB)
     |████████████████████████████████| 228.8 MB 23 kB/s
Collecting tbb==2021.*
  Downloading tbb-2021.1.1-py3-none-win_amd64.whl (254 kB)
     |████████████████████████████████| 254 kB 2.2 MB/s
Installing collected packages: tbb, intel-openmp, mkl
Successfully installed intel-openmp-2021.1.2 mkl-2021.1.1 tbb-2021.1.1

(venv_vibe) C:\MOCAP1\VIBE>pip install torch==1.4.0 torchvision==0.5.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.4.0
  Downloading https://download.pytorch.org/whl/cu92/torch-1.4.0%2Bcu92-cp37-cp37m-win_amd64.whl (641.8 MB)
     |████████████████████████████████| 641.8 MB 16 kB/s
Collecting torchvision==0.5.0
  Downloading https://download.pytorch.org/whl/cu92/torchvision-0.5.0%2Bcu92-cp37-cp37m-win_amd64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 6.4 MB/s
Collecting pillow>=4.1.1
  Downloading Pillow-8.1.0-cp37-cp37m-win_amd64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 3.2 MB/s
Collecting numpy
  Downloading numpy-1.20.1-cp37-cp37m-win_amd64.whl (13.6 MB)
     |████████████████████████████████| 13.6 MB 6.4 MB/s
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: torch, six, pillow, numpy, torchvision
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
virtualenv 20.0.27 requires appdirs<2,>=1.4.3, which is not installed.
virtualenv 20.0.27 requires importlib-metadata<2,>=0.12; python_version < "3.8", which is not installed.
Successfully installed numpy-1.20.1 pillow-8.1.0 six-1.15.0 torch-1.4.0+cu92 torchvision-0.5.0+cu92

(venv_vibe) C:\MOCAP1\VIBE>pip install numpy==1.17.5
Collecting numpy==1.17.5
  Downloading numpy-1.17.5-cp37-cp37m-win_amd64.whl (12.7 MB)
     |████████████████████████████████| 12.7 MB 595 kB/s
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.1
    Uninstalling numpy-1.20.1:
      Successfully uninstalled numpy-1.20.1
Successfully installed numpy-1.17.5

(venv_vibe) C:\MOCAP1\VIBE>pip install git+https://github.com/giacaglia/pytube.git --upgrade
Collecting git+https://github.com/giacaglia/pytube.git
  Cloning https://github.com/giacaglia/pytube.git to c:\users\moust\appdata\local\temp\pip-req-build-il4wt0mm
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/giacaglia/pytube.git 'C:\Users\moust\AppData\Local\Temp\pip-req-build-il4wt0mm'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

(venv_vibe) C:\MOCAP1\VIBE>pip install -r requirements_alter.txt
Requirement already satisfied: numpy==1.17.5 in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 4)) (1.17.5)
Requirement already satisfied: torchvision==0.5.0 in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 18)) (0.5.0+cu92)
Collecting git+https://github.com/mattloper/chumpy.git (from -r requirements_alter.txt (line 23))
  Cloning https://github.com/mattloper/chumpy.git to c:\users\moust\appdata\local\temp\pip-req-build-ulvmpq4b
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/mattloper/chumpy.git 'C:\Users\moust\AppData\Local\Temp\pip-req-build-ulvmpq4b'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

(venv_vibe) C:\MOCAP1\VIBE>conda install -c anaconda git
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\moust\miniconda3\envs\venv_vibe

  added / updated specs:
    - git

The following NEW packages will be INSTALLED:

  git                anaconda/win-64::git-2.23.0-h6bb4b03_0

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2021.1.19-~ --> anaconda::ca-certificates-2020.10.14-0
  certifi            pkgs/main::certifi-2020.12.5-py37haa9~ --> anaconda::certifi-2020.6.20-py37_0
  openssl              pkgs/main::openssl-1.1.1i-h2bbff1b_0 --> anaconda::openssl-1.1.1h-he774522_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(venv_vibe) C:\MOCAP1\VIBE>install_conda.bat

(venv_vibe) C:\MOCAP1\VIBE>pip install mkl intel-openmp
Requirement already satisfied: mkl in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (2021.1.1)
Requirement already satisfied: intel-openmp in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (2021.1.2)
Requirement already satisfied: tbb==2021.* in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (from mkl) (2021.1.1)

(venv_vibe) C:\MOCAP1\VIBE>pip install torch==1.4.0 torchvision==0.5.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Requirement already satisfied: torch==1.4.0 in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (1.4.0+cu92)
Requirement already satisfied: torchvision==0.5.0 in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (0.5.0+cu92)
Requirement already satisfied: pillow>=4.1.1 in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (from torchvision==0.5.0) (8.1.0)
Requirement already satisfied: six in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (from torchvision==0.5.0) (1.15.0)
Requirement already satisfied: numpy in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (from torchvision==0.5.0) (1.17.5)

(venv_vibe) C:\MOCAP1\VIBE>pip install numpy==1.17.5
Requirement already satisfied: numpy==1.17.5 in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (1.17.5)

(venv_vibe) C:\MOCAP1\VIBE>pip install git+https://github.com/giacaglia/pytube.git --upgrade
Collecting git+https://github.com/giacaglia/pytube.git
  Cloning https://github.com/giacaglia/pytube.git to c:\users\moust\appdata\local\temp\pip-req-build-6594kvqh
Building wheels for collected packages: pytube
  Building wheel for pytube (setup.py) ... done
  Created wheel for pytube: filename=pytube-9.5.3-py3-none-any.whl size=29188 sha256=a7f65de91378b47effb039ea24fe4db6aae8af4f061f7f8645e9f6f97f13d062
  Stored in directory: C:\Users\moust\AppData\Local\Temp\pip-ephem-wheel-cache-x4a44v5e\wheels\ca\b9\e4\f14415300036c42fae7c12b5dd718f0e8a10e29184fc82eb47
Successfully built pytube
Installing collected packages: pytube
Successfully installed pytube-9.5.3

(venv_vibe) C:\MOCAP1\VIBE>pip install -r requirements_alter.txt
Requirement already satisfied: numpy==1.17.5 in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 4)) (1.17.5)
Requirement already satisfied: torchvision==0.5.0 in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 18)) (0.5.0+cu92)
Collecting git+https://github.com/mattloper/chumpy.git (from -r requirements_alter.txt (line 23))
  Cloning https://github.com/mattloper/chumpy.git to c:\users\moust\appdata\local\temp\pip-req-build-0_wkc8of
Collecting git+https://github.com/mkocabas/yolov3-pytorch.git (from -r requirements_alter.txt (line 24))
  Cloning https://github.com/mkocabas/yolov3-pytorch.git to c:\users\moust\appdata\local\temp\pip-req-build-lgzocjgo
Collecting git+https://github.com/mkocabas/multi-person-tracker.git (from -r requirements_alter.txt (line 25))
  Cloning https://github.com/mkocabas/multi-person-tracker.git to c:\users\moust\appdata\local\temp\pip-req-build-68jncd_f
Requirement already satisfied: six>=1.11.0 in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (from chumpy==0.70->-r requirements_alter.txt (line 23)) (1.15.0)
Collecting filterpy==1.4.5
  Downloading filterpy-1.4.5.zip (177 kB)
     |████████████████████████████████| 177 kB 1.6 MB/s
Collecting gdown==3.6.4
  Downloading gdown-3.6.4.tar.gz (5.2 kB)
Collecting h5py==2.10.0
  Downloading h5py-2.10.0-cp37-cp37m-win_amd64.whl (2.5 MB)
     |████████████████████████████████| 2.5 MB 3.3 MB/s
Collecting joblib==0.14.1
  Downloading joblib-0.14.1-py2.py3-none-any.whl (294 kB)
     |████████████████████████████████| 294 kB 3.3 MB/s
Collecting llvmlite==0.32.1
  Downloading llvmlite-0.32.1-cp37-cp37m-win_amd64.whl (13.6 MB)
     |████████████████████████████████| 13.6 MB 1.6 MB/s
Collecting matplotlib==3.1.3
  Downloading matplotlib-3.1.3-cp37-cp37m-win_amd64.whl (9.1 MB)
     |████████████████████████████████| 9.1 MB 2.2 MB/s
Collecting numba==0.47.0
  Downloading numba-0.47.0-cp37-cp37m-win_amd64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 3.3 MB/s
Requirement already satisfied: setuptools in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (from numba==0.47.0->-r requirements_alter.txt (line 6)) (52.0.0.post20210125)
Collecting opencv-python==4.1.2.30
  Downloading opencv_python-4.1.2.30-cp37-cp37m-win_amd64.whl (33.0 MB)
     |████████████████████████████████| 33.0 MB 3.3 MB/s
Collecting pillow==7.1.0
  Downloading Pillow-7.1.0-cp37-cp37m-win_amd64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 1.3 MB/s
Collecting progress==1.5
  Downloading progress-1.5.tar.gz (5.8 kB)
Collecting pyrender==0.1.36
  Downloading pyrender-0.1.36-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 2.2 MB/s
Collecting PyYAML==5.3.1
  Downloading PyYAML-5.3.1-cp37-cp37m-win_amd64.whl (216 kB)
     |████████████████████████████████| 216 kB 3.3 MB/s
Collecting scikit-image==0.16.2
  Downloading scikit_image-0.16.2-cp37-cp37m-win_amd64.whl (25.7 MB)
     |████████████████████████████████| 25.7 MB 233 kB/s
Collecting scikit-video==1.1.11
  Downloading scikit_video-1.1.11-py2.py3-none-any.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 6.4 MB/s
Collecting scipy==1.4.1
  Downloading scipy-1.4.1-cp37-cp37m-win_amd64.whl (30.9 MB)
     |████████████████████████████████| 30.9 MB 3.3 MB/s
Collecting smplx==0.1.26
  Using cached smplx-0.1.26-py3-none-any.whl (29 kB)
Requirement already satisfied: torch>=1.0.1.post2 in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (from smplx==0.1.26->-r requirements_alter.txt (line 7)) (1.4.0+cu92)
Collecting tensorflow==1.15.4
  Downloading tensorflow-1.15.4-cp37-cp37m-win_amd64.whl (55.3 MB)
     |████████████████████████████████| 55.3 MB 89 kB/s
Requirement already satisfied: wheel>=0.26 in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (0.36.2)
Collecting tqdm==4.28.1
  Downloading tqdm-4.28.1-py2.py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 3.4 MB/s
Collecting trimesh==3.5.25
  Downloading trimesh-3.5.25.tar.gz (399 kB)
     |████████████████████████████████| 399 kB 6.4 MB/s
Collecting yacs==0.1.6
  Downloading yacs-0.1.6-py3-none-any.whl (9.6 kB)
Collecting gast==0.2.2
  Downloading gast-0.2.2.tar.gz (10 kB)
Collecting PyOpenGL==3.1.0
  Downloading PyOpenGL-3.1.0.zip (2.2 MB)
     |████████████████████████████████| 2.2 MB 1.6 MB/s
Collecting tensorflow-estimator==1.15.1
  Downloading tensorflow_estimator-1.15.1-py2.py3-none-any.whl (503 kB)
     |████████████████████████████████| 503 kB 3.3 MB/s
Collecting absl-py>=0.7.0
  Using cached absl_py-0.11.0-py3-none-any.whl (127 kB)
Collecting astor>=0.6.0
  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting google-pasta>=0.1.6
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 4.1 MB/s
Collecting grpcio>=1.8.6
  Using cached grpcio-1.35.0-cp37-cp37m-win_amd64.whl (3.0 MB)
Collecting imageio
  Downloading imageio-2.9.0-py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 6.4 MB/s
Collecting keras-applications>=1.0.8
  Downloading Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
     |████████████████████████████████| 50 kB 3.2 MB/s
Collecting keras-preprocessing>=1.0.5
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 3.2 MB/s
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.1-cp37-cp37m-win_amd64.whl (51 kB)
Collecting networkx
  Downloading networkx-2.5-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 6.4 MB/s
Collecting decorator>=4.3.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting opt-einsum>=2.3.2
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 4.8 MB/s
Collecting protobuf>=3.6.1
  Using cached protobuf-3.14.0-cp37-cp37m-win_amd64.whl (798 kB)
Collecting pyglet>=1.4.10
  Downloading pyglet-1.5.15-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB ...
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting PyWavelets>=0.4.0
  Downloading PyWavelets-1.1.1-cp37-cp37m-win_amd64.whl (4.2 MB)
     |████████████████████████████████| 4.2 MB 3.2 MB/s
Collecting tensorboard<1.16.0,>=1.15.0
  Downloading tensorboard-1.15.0-py3-none-any.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 6.4 MB/s
Collecting markdown>=2.6.8
  Using cached Markdown-3.3.3-py3-none-any.whl (96 kB)
Collecting termcolor>=1.1.0
  Using cached termcolor-1.1.0-py3-none-any.whl
Collecting torchgeometry>=0.1.2
  Using cached torchgeometry-0.1.2-py2.py3-none-any.whl (42 kB)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting wrapt>=1.11.1
  Downloading wrapt-1.12.1.tar.gz (27 kB)
Collecting freetype-py
  Downloading freetype_py-2.2.0-py3-none-win_amd64.whl (708 kB)
     |████████████████████████████████| 708 kB 3.3 MB/s
Collecting importlib-metadata
  Using cached importlib_metadata-3.4.0-py3-none-any.whl (10 kB)
Collecting typing-extensions>=3.6.4
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting zipp>=0.5
  Using cached zipp-3.4.0-py3-none-any.whl (5.2 kB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\moust\miniconda3\envs\venv_vibe\lib\site-packages (from requests->gdown==3.6.4->-r requirements_alter.txt (line 8)) (2020.6.20)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Building wheels for collected packages: chumpy, multi-person-tracker, yolov3, filterpy, gdown, progress, trimesh, gast, PyOpenGL, wrapt
  Building wheel for chumpy (setup.py) ... done
  Created wheel for chumpy: filename=chumpy-0.70-py3-none-any.whl size=61409 sha256=039f1bcf954b8790226875f6805db48a8e3261531e7a340357418288d436088c
  Stored in directory: C:\Users\moust\AppData\Local\Temp\pip-ephem-wheel-cache-ftl6t0qz\wheels\75\79\0c\28691a1142ad051800aef1054a725eae9e73c1571b28c3afe4
  Building wheel for multi-person-tracker (setup.py) ... done
  Created wheel for multi-person-tracker: filename=multi_person_tracker-0.1-py3-none-any.whl size=8955 sha256=38b33508b3c4133e06c22ea4d2b8db3e4ccfd23bf989675cb33489a73748d67e
  Stored in directory: C:\Users\moust\AppData\Local\Temp\pip-ephem-wheel-cache-ftl6t0qz\wheels\87\95\a8\a3d2cc559da199a1ff9243d1a8ef95563cba313ec7344bf895
  Building wheel for yolov3 (setup.py) ... done
  Created wheel for yolov3: filename=yolov3-0.1-py3-none-any.whl size=26079 sha256=85ddf4b537a4306a02f34666cdae6dbd2e7453d0a3c77a0c561fbb737552a6cc
  Stored in directory: C:\Users\moust\AppData\Local\Temp\pip-ephem-wheel-cache-ftl6t0qz\wheels\22\16\d8\9908e762166d022a96b6f33ffe2c3771dbc88accfff9c68189
  Building wheel for filterpy (setup.py) ... done
  Created wheel for filterpy: filename=filterpy-1.4.5-py3-none-any.whl size=110451 sha256=9dfa81baac978bd0462b94290c24a87bb5266dc6f7e8fa3d0ac751ab185b2d5b
  Stored in directory: c:\users\moust\appdata\local\pip\cache\wheels\ce\e0\ee\a2b3c5caab3418c1ccd8c4de573d4cbe13315d7e8b0a55fbc2
  Building wheel for gdown (setup.py) ... done
  Created wheel for gdown: filename=gdown-3.6.4-py3-none-any.whl size=6122 sha256=9b8e8591fe53a9ab466f7bfc5399b99674f85ce1a892c09ff64228b5ff1e1769
  Stored in directory: c:\users\moust\appdata\local\pip\cache\wheels\30\38\96\2cc763113a589e09b7c3e3e9f8efe349377804de3afb46dca8
  Building wheel for progress (setup.py) ... done
  Created wheel for progress: filename=progress-1.5-py3-none-any.whl size=8073 sha256=b59b5db542eefa508f2fd1a3472d6dfa0ad69cdccd7295103456fdbe9f20326b
  Stored in directory: c:\users\moust\appdata\local\pip\cache\wheels\4c\ff\85\0cabf2cb317421028ef98853ae5c8d84c31f3e4e11862ea977
  Building wheel for trimesh (setup.py) ... done
  Created wheel for trimesh: filename=trimesh-3.5.25-py3-none-any.whl size=452611 sha256=1209691c7e6d698803f83c1339e2dbe69e88384cf422e2f413951ffe68d8ad39
  Stored in directory: c:\users\moust\appdata\local\pip\cache\wheels\bd\5e\96\41a7b640b964232036bb4ddb7f4f945ebef9afafa6fb200d8c
  Building wheel for gast (setup.py) ... done
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7538 sha256=85e9fc7010e49fcce8046c703dffa9194fec02863840de5c7a1529ee1ad88dc1
  Stored in directory: c:\users\moust\appdata\local\pip\cache\wheels\21\7f\02\420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
  Building wheel for PyOpenGL (setup.py) ... done
  Created wheel for PyOpenGL: filename=PyOpenGL-3.1.0-py3-none-any.whl size=1749281 sha256=b7ef847dcdd1d97991d4d6c49bf1433e82d941d14b15dd6bbab9b68b89877521
  Stored in directory: c:\users\moust\appdata\local\pip\cache\wheels\c6\83\cb\af51a0c06c33d08537b941bbfc87469e8a3c68d05f77a6a212
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.12.1-cp37-cp37m-win_amd64.whl size=33405 sha256=32a5e9d48d420b6cc25c8cf6e86f5ad094f665ec5624e977ea1c5b9063133206
  Stored in directory: c:\users\moust\appdata\local\pip\cache\wheels\62\76\4c\aa25851149f3f6d9785f6c869387ad82b3fd37582fa8147ac6
Successfully built chumpy multi-person-tracker yolov3 filterpy gdown progress trimesh gast PyOpenGL wrapt
Installing collected packages: zipp, typing-extensions, importlib-metadata, werkzeug, urllib3, python-dateutil, pyparsing, protobuf, pillow, markdown, kiwisolver, idna, h5py, grpcio, decorator, cycler, chardet, absl-py, wrapt, trimesh, tqdm, torchgeometry, termcolor, tensorflow-estimator, tensorboard, scipy, requests, PyYAML, PyWavelets, PyOpenGL, pyglet, opt-einsum, networkx, matplotlib, llvmlite, keras-preprocessing, keras-applications, imageio, google-pasta, gast, freetype-py, astor, yolov3, yacs, tensorflow, smplx, scikit-video, scikit-image, pyrender, progress, opencv-python, numba, multi-person-tracker, joblib, gdown, filterpy, chumpy
  Attempting uninstall: pillow
    Found existing installation: Pillow 8.1.0
    Uninstalling Pillow-8.1.0:
      Successfully uninstalled Pillow-8.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
virtualenv 20.0.27 requires appdirs<2,>=1.4.3, which is not installed.
virtualenv 20.0.27 requires importlib-metadata<2,>=0.12; python_version < "3.8", but you have importlib-metadata 3.4.0 which is incompatible.
Successfully installed PyOpenGL-3.1.0 PyWavelets-1.1.1 PyYAML-5.3.1 absl-py-0.11.0 astor-0.8.1 chardet-4.0.0 chumpy-0.70 cycler-0.10.0 decorator-4.4.2 filterpy-1.4.5 freetype-py-2.2.0 gast-0.2.2 gdown-3.6.4 google-pasta-0.2.0 grpcio-1.35.0 h5py-2.10.0 idna-2.10 imageio-2.9.0 importlib-metadata-3.4.0 joblib-0.14.1 keras-applications-1.0.8 keras-preprocessing-1.1.2 kiwisolver-1.3.1 llvmlite-0.32.1 markdown-3.3.3 matplotlib-3.1.3 multi-person-tracker-0.1 networkx-2.5 numba-0.47.0 opencv-python-4.1.2.30 opt-einsum-3.3.0 pillow-7.1.0 progress-1.5 protobuf-3.14.0 pyglet-1.5.15 pyparsing-2.4.7 pyrender-0.1.36 python-dateutil-2.8.1 requests-2.25.1 scikit-image-0.16.2 scikit-video-1.1.11 scipy-1.4.1 smplx-0.1.26 tensorboard-1.15.0 tensorflow-1.15.4 tensorflow-estimator-1.15.1 termcolor-1.1.0 torchgeometry-0.1.2 tqdm-4.28.1 trimesh-3.5.25 typing-extensions-3.7.4.3 urllib3-1.26.3 werkzeug-1.0.1 wrapt-1.12.1 yacs-0.1.6 yolov3-0.1 zipp-3.4.0

(venv_vibe) C:\MOCAP1\VIBE>prepare_data.bat

(venv_vibe) C:\MOCAP1\VIBE>md data

(venv_vibe) C:\MOCAP1\VIBE>cd data

(venv_vibe) C:\MOCAP1\VIBE\data>gdown "https://drive.google.com/uc?id=1untXhYOLQtpNEy4GTY_0fL_H-k6cTf_r"
Downloading...
From: https://drive.google.com/uc?id=1untXhYOLQtpNEy4GTY_0fL_H-k6cTf_r
To: C:\MOCAP1\VIBE\data\vibe_data.zip
561MB [02:21, 3.97MB/s]

(venv_vibe) C:\MOCAP1\VIBE\data>cd ..

(venv_vibe) C:\MOCAP1\VIBE>echo #### Extract the files from vibe_data ###
#### Extract the files from vibe_data ###

(venv_vibe) C:\MOCAP1\VIBE>python unzip_vibe_data.py

(venv_vibe) C:\MOCAP1\VIBE>copy data\vibe_data\sample_video.mp4 .
        1 file(s) copied.

(venv_vibe) C:\MOCAP1\VIBE>echo ### creating place for torch model ###
### creating place for torch model ###

(venv_vibe) C:\MOCAP1\VIBE>md \Users\moust\.torch\models

(venv_vibe) C:\MOCAP1\VIBE>copy data\vibe_data\yolov3.weights \Users\moust\.torch\models
        1 file(s) copied.

(venv_vibe) C:\MOCAP1\VIBE>echo ### creating place for yolo config ###
### creating place for yolo config ###

(venv_vibe) C:\MOCAP1\VIBE>md \Users\moust\.torch\config

(venv_vibe) C:\MOCAP1\VIBE>copy yolov3.cfg \Users\moust\.torch\config
        1 file(s) copied.

(venv_vibe) C:\MOCAP1\VIBE>conda activate venv_vibe

(venv_vibe) C:\MOCAP1\VIBE>python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp\sample_video_mp4/%06d.png"
Traceback (most recent call last):
  File "demo_alter.py", line 405, in <module>
    main(args)
  File "demo_alter.py", line 72, in main
    image_folder, num_frames, img_shape = video_to_images(video_file, return_info=True)
  File "C:\MOCAP1\VIBE\lib\utils\demo_utils.py", line 195, in video_to_images
    subprocess.call(command)
  File "C:\Users\moust\miniconda3\envs\venv_vibe\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\moust\miniconda3\envs\venv_vibe\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\moust\miniconda3\envs\venv_vibe\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by carlosedubarreto** [comment]
looks like a problem with git

plese try this command and run the installation again

conda install -c anaconda git

**Comment by carlosedubarreto** [comment]
Closing after long time without response
