### ISSUE TITLE
Error:  No module named 'cv2'

### ISSUE THREAD

**Issue by Tijndel** [carlosedubarreto/vibe_win_install#7]
when i run the command: 'python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display' it says:
 ' File "demo_alter.py", line 20, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2''
can someone please help me? i am a beginner and don't know what to do.

**Comment by carlosedubarreto** [comment]
Looks like you have a problem with OpenCV.
The requirements_alter should have installed that.

Please do the instalation from the beggining and share the results that show up on your screen. Paste them here.

**Comment by Tijndel** [comment]
![Afbeelding1](https://user-images.githubusercontent.com/80905789/111762873-ca4ba780-88a1-11eb-94a2-24b1e4f4a237.png)
this is what my folder looks like.
![image](https://user-images.githubusercontent.com/80905789/111763078-02eb8100-88a2-11eb-8e8e-a2d238002724.png)
i got these errors when i ran the command 'install_conda.bat'.

**Comment by carlosedubarreto** [comment]
The error it is showing here is a problem with git python module.

try to install it using:
`conda install -c anaconda git`

**Comment by Tijndel** [comment]
it still gives the same error.

**Comment by carlosedubarreto** [comment]
Thats odd. the error states  you to add the git to your path.
Can you try that?

**Comment by Tijndel** [comment]
what is the git?

**Comment by carlosedubarreto** [comment]
git is an aplication that makes you donwload packages throught command line.

can you try this again and show me what shows on your screen?

go to your virtual enviroment
`conda activate venv_vibe`

got to the folder of vibe
`cd mocap\VIBE-master`
run
`conda install -c anaconda git`

and then run the installation again
`install_conda.bat`
`prepare_data.bat`

**Comment by Tijndel** [comment]
(base) C:\Users\User>conda activate venv_vibe

(venv_vibe) C:\Users\User>cd MOCAP\VIBE-master
Het systeem kan het opgegeven pad niet vinden.

(venv_vibe) C:\Users\User>cd\

(venv_vibe) C:\>cd mocap\VIBE-master

(venv_vibe) C:\MOCAP\VIBE-master>conda install -c anaconda git
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


(venv_vibe) C:\MOCAP\VIBE-master>install_conda.bat

(venv_vibe) C:\MOCAP\VIBE-master>pip install mkl intel-openmp
Collecting mkl
  Using cached mkl-2021.1.1-py2.py3-none-win_amd64.whl (228.8 MB)
Collecting intel-openmp
  Using cached intel_openmp-2021.1.2-py2.py3-none-win_amd64.whl (3.3 MB)
Collecting tbb==2021.*
  Using cached tbb-2021.1.1-py3-none-win_amd64.whl (254 kB)
Installing collected packages: tbb, intel-openmp, mkl
Successfully installed intel-openmp-2021.1.2 mkl-2021.1.1 tbb-2021.1.1

(venv_vibe) C:\MOCAP\VIBE-master>pip install torch==1.4.0 torchvision==0.5.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.4.0
  Using cached https://download.pytorch.org/whl/cu92/torch-1.4.0%2Bcu92-cp37-cp37m-win_amd64.whl (641.8 MB)
Collecting torchvision==0.5.0
  Using cached https://download.pytorch.org/whl/cu92/torchvision-0.5.0%2Bcu92-cp37-cp37m-win_amd64.whl (1.2 MB)
Collecting pillow>=4.1.1
  Using cached Pillow-8.1.2-cp37-cp37m-win_amd64.whl (2.2 MB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting numpy
  Using cached numpy-1.20.1-cp37-cp37m-win_amd64.whl (13.6 MB)
Installing collected packages: torch, six, pillow, numpy, torchvision
Successfully installed numpy-1.20.1 pillow-8.1.2 six-1.15.0 torch-1.4.0+cu92 torchvision-0.5.0+cu92

(venv_vibe) C:\MOCAP\VIBE-master>pip install numpy==1.17.5
Collecting numpy==1.17.5
  Using cached numpy-1.17.5-cp37-cp37m-win_amd64.whl (12.7 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.1
    Uninstalling numpy-1.20.1:
      Successfully uninstalled numpy-1.20.1
Successfully installed numpy-1.17.5

(venv_vibe) C:\MOCAP\VIBE-master>pip install git+https://github.com/giacaglia/pytube.git --upgrade
Collecting git+https://github.com/giacaglia/pytube.git
  Cloning https://github.com/giacaglia/pytube.git to c:\users\user\appdata\local\temp\pip-req-build-fahkqk33
  Running command git clone -q https://github.com/giacaglia/pytube.git 'C:\Users\User\AppData\Local\Temp\pip-req-build-fahkqk33'
Building wheels for collected packages: pytube
  Building wheel for pytube (setup.py) ... done
  Created wheel for pytube: filename=pytube-9.5.3-py3-none-any.whl size=29188 sha256=3de700f38fefbbfdfc2c72e8858217852b89d728c30d3fbb4493bf0db0818511
  Stored in directory: C:\Users\User\AppData\Local\Temp\pip-ephem-wheel-cache-w0jmp83y\wheels\ca\b9\e4\f14415300036c42fae7c12b5dd718f0e8a10e29184fc82eb47
Successfully built pytube
Installing collected packages: pytube
Successfully installed pytube-9.5.3

(venv_vibe) C:\MOCAP\VIBE-master>pip install -r requirements_alter.txt
Collecting git+https://github.com/mattloper/chumpy.git (from -r requirements_alter.txt (line 23))
  Cloning https://github.com/mattloper/chumpy.git to c:\users\user\appdata\local\temp\pip-req-build-q9v266nq
  Running command git clone -q https://github.com/mattloper/chumpy.git 'C:\Users\User\AppData\Local\Temp\pip-req-build-q9v266nq'
Collecting git+https://github.com/mkocabas/yolov3-pytorch.git (from -r requirements_alter.txt (line 24))
  Cloning https://github.com/mkocabas/yolov3-pytorch.git to c:\users\user\appdata\local\temp\pip-req-build-xnqnnr00
  Running command git clone -q https://github.com/mkocabas/yolov3-pytorch.git 'C:\Users\User\AppData\Local\Temp\pip-req-build-xnqnnr00'
Collecting git+https://github.com/mkocabas/multi-person-tracker.git (from -r requirements_alter.txt (line 25))
  Cloning https://github.com/mkocabas/multi-person-tracker.git to c:\users\user\appdata\local\temp\pip-req-build-c9qqmjav
  Running command git clone -q https://github.com/mkocabas/multi-person-tracker.git 'C:\Users\User\AppData\Local\Temp\pip-req-build-c9qqmjav'
Collecting tqdm==4.28.1
  Downloading tqdm-4.28.1-py2.py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 1.1 MB/s
Collecting yacs==0.1.6
  Downloading yacs-0.1.6-py3-none-any.whl (9.6 kB)
Collecting h5py==2.10.0
  Downloading h5py-2.10.0-cp37-cp37m-win_amd64.whl (2.5 MB)
     |████████████████████████████████| 2.5 MB 6.8 MB/s
Requirement already satisfied: numpy==1.17.5 in c:\users\user\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 4)) (1.17.5)
Collecting scipy==1.4.1
  Downloading scipy-1.4.1-cp37-cp37m-win_amd64.whl (30.9 MB)
     |████████████████████████████████| 30.9 MB 6.4 MB/s
Collecting numba==0.47.0
  Downloading numba-0.47.0-cp37-cp37m-win_amd64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 3.3 MB/s
Collecting smplx==0.1.26
  Downloading smplx-0.1.26-py3-none-any.whl (29 kB)
Collecting gdown==3.6.4
  Downloading gdown-3.6.4.tar.gz (5.2 kB)
Collecting PyYAML==5.3.1
  Downloading PyYAML-5.3.1-cp37-cp37m-win_amd64.whl (216 kB)
     |████████████████████████████████| 216 kB 6.4 MB/s
Collecting joblib==0.14.1
  Downloading joblib-0.14.1-py2.py3-none-any.whl (294 kB)
     |████████████████████████████████| 294 kB 6.4 MB/s
Collecting pillow==7.1.0
  Downloading Pillow-7.1.0-cp37-cp37m-win_amd64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 6.8 MB/s
Collecting trimesh==3.5.25
  Downloading trimesh-3.5.25.tar.gz (399 kB)
     |████████████████████████████████| 399 kB 6.8 MB/s
Collecting pyrender==0.1.36
  Downloading pyrender-0.1.36-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 6.8 MB/s
Collecting progress==1.5
  Downloading progress-1.5.tar.gz (5.8 kB)
Collecting filterpy==1.4.5
  Downloading filterpy-1.4.5.zip (177 kB)
     |████████████████████████████████| 177 kB 6.4 MB/s
Collecting matplotlib==3.1.3
  Downloading matplotlib-3.1.3-cp37-cp37m-win_amd64.whl (9.1 MB)
     |████████████████████████████████| 9.1 MB 3.3 MB/s
Collecting tensorflow==1.15.4
  Downloading tensorflow-1.15.4-cp37-cp37m-win_amd64.whl (55.3 MB)
     |████████████████████████████████| 55.3 MB 6.4 MB/s
Requirement already satisfied: torchvision==0.5.0 in c:\users\user\miniconda3\envs\venv_vibe\lib\site-packages (from -r requirements_alter.txt (line 18)) (0.5.0+cu92)
Collecting scikit-image==0.16.2
  Downloading scikit_image-0.16.2-cp37-cp37m-win_amd64.whl (25.7 MB)
     |████████████████████████████████| 25.7 MB 6.4 MB/s
Collecting scikit-video==1.1.11
  Downloading scikit_video-1.1.11-py2.py3-none-any.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB ...
Collecting opencv-python==4.1.2.30
  Downloading opencv_python-4.1.2.30-cp37-cp37m-win_amd64.whl (33.0 MB)
     |████████████████████████████████| 33.0 MB 2.2 MB/s
Collecting llvmlite==0.32.1
  Downloading llvmlite-0.32.1-cp37-cp37m-win_amd64.whl (13.6 MB)
     |████████████████████████████████| 13.6 MB 6.4 MB/s
Requirement already satisfied: six>=1.11.0 in c:\users\user\miniconda3\envs\venv_vibe\lib\site-packages (from chumpy==0.70->-r requirements_alter.txt (line 23)) (1.15.0)
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 2.0 MB/s
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.1-cp37-cp37m-win_amd64.whl (51 kB)
     |████████████████████████████████| 51 kB 46 kB/s
Collecting python-dateutil>=2.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 6.4 MB/s
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 1.7 MB/s
Requirement already satisfied: setuptools in c:\users\user\miniconda3\envs\venv_vibe\lib\site-packages (from numba==0.47.0->-r requirements_alter.txt (line 6)) (52.0.0.post20210125)
Collecting freetype-py
  Downloading freetype_py-2.2.0-py3-none-win_amd64.whl (708 kB)
     |████████████████████████████████| 708 kB 3.2 MB/s
Collecting pyglet>=1.4.10
  Downloading pyglet-1.5.15-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 3.2 MB/s
Collecting imageio
  Downloading imageio-2.9.0-py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 6.4 MB/s
Collecting PyOpenGL==3.1.0
  Downloading PyOpenGL-3.1.0.zip (2.2 MB)
     |████████████████████████████████| 2.2 MB 6.8 MB/s
Collecting networkx
  Downloading networkx-2.5-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 6.4 MB/s
Collecting PyWavelets>=0.4.0
  Downloading PyWavelets-1.1.1-cp37-cp37m-win_amd64.whl (4.2 MB)
     |████████████████████████████████| 4.2 MB 6.8 MB/s
Requirement already satisfied: torch>=1.0.1.post2 in c:\users\user\miniconda3\envs\venv_vibe\lib\site-packages (from smplx==0.1.26->-r requirements_alter.txt (line 7)) (1.4.0+cu92)
Collecting torchgeometry>=0.1.2
  Downloading torchgeometry-0.1.2-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 478 kB/s
Collecting protobuf>=3.6.1
  Downloading protobuf-3.15.6-cp37-cp37m-win_amd64.whl (904 kB)
     |████████████████████████████████| 904 kB 6.4 MB/s
Collecting absl-py>=0.7.0
  Downloading absl_py-0.12.0-py3-none-any.whl (129 kB)
     |████████████████████████████████| 129 kB 6.8 MB/s
Collecting tensorboard<1.16.0,>=1.15.0
  Downloading tensorboard-1.15.0-py3-none-any.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 3.2 MB/s
Collecting tensorflow-estimator==1.15.1
  Downloading tensorflow_estimator-1.15.1-py2.py3-none-any.whl (503 kB)
     |████████████████████████████████| 503 kB 6.8 MB/s
Collecting wrapt>=1.11.1
  Downloading wrapt-1.12.1.tar.gz (27 kB)
Collecting termcolor>=1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
Collecting keras-applications>=1.0.8
  Downloading Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
     |████████████████████████████████| 50 kB 3.2 MB/s
Collecting keras-preprocessing>=1.0.5
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 506 kB/s
Requirement already satisfied: wheel>=0.26 in c:\users\user\miniconda3\envs\venv_vibe\lib\site-packages (from tensorflow==1.15.4->-r requirements_alter.txt (line 17)) (0.36.2)
Collecting grpcio>=1.8.6
  Downloading grpcio-1.36.1-cp37-cp37m-win_amd64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 6.4 MB/s
Collecting astor>=0.6.0
  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting google-pasta>=0.1.6
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 3.8 MB/s
Collecting opt-einsum>=2.3.2
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 1.8 MB/s
Collecting gast==0.2.2
  Downloading gast-0.2.2.tar.gz (10 kB)
Collecting decorator>=4.3.0
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting markdown>=2.6.8
  Downloading Markdown-3.3.4-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 6.4 MB/s
Collecting werkzeug>=0.11.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
     |████████████████████████████████| 298 kB 6.8 MB/s
Collecting importlib-metadata
  Downloading importlib_metadata-3.7.3-py3-none-any.whl (12 kB)
Collecting zipp>=0.5
  Downloading zipp-3.4.1-py3-none-any.whl (5.2 kB)
Collecting typing-extensions>=3.6.4
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB ...
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 6.4 MB/s
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\miniconda3\envs\venv_vibe\lib\site-packages (from requests->gdown==3.6.4->-r requirements_alter.txt (line 8)) (2020.6.20)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB 6.4 MB/s
Building wheels for collected packages: chumpy, multi-person-tracker, yolov3, filterpy, gdown, progress, trimesh, gast, PyOpenGL, termcolor, wrapt
  Building wheel for chumpy (setup.py) ... done
  Created wheel for chumpy: filename=chumpy-0.70-py3-none-any.whl size=61409 sha256=78ed11925f35346765fcb803a2d463c57f9dccce8372f22f5511db107014b981
  Stored in directory: C:\Users\User\AppData\Local\Temp\pip-ephem-wheel-cache-h7g29sat\wheels\75\79\0c\28691a1142ad051800aef1054a725eae9e73c1571b28c3afe4
  Building wheel for multi-person-tracker (setup.py) ... done
  Created wheel for multi-person-tracker: filename=multi_person_tracker-0.1-py3-none-any.whl size=8955 sha256=e1c53e346e7ebf9bcd9b9b8fd707d1b8816373aaabb39074e1bf24d8b3bb945a
  Stored in directory: C:\Users\User\AppData\Local\Temp\pip-ephem-wheel-cache-h7g29sat\wheels\87\95\a8\a3d2cc559da199a1ff9243d1a8ef95563cba313ec7344bf895
  Building wheel for yolov3 (setup.py) ... done
  Created wheel for yolov3: filename=yolov3-0.1-py3-none-any.whl size=26079 sha256=e92ddf36c318b636c79286fa2d78a88ef3a172367f1cb895a7014b383bda5c61
  Stored in directory: C:\Users\User\AppData\Local\Temp\pip-ephem-wheel-cache-h7g29sat\wheels\22\16\d8\9908e762166d022a96b6f33ffe2c3771dbc88accfff9c68189
  Building wheel for filterpy (setup.py) ... done
  Created wheel for filterpy: filename=filterpy-1.4.5-py3-none-any.whl size=110451 sha256=ab82b6ca54067a125fdf13bb90647a82e0e6b2e970e566a302c728a337e6eb56
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\ce\e0\ee\a2b3c5caab3418c1ccd8c4de573d4cbe13315d7e8b0a55fbc2
  Building wheel for gdown (setup.py) ... done
  Created wheel for gdown: filename=gdown-3.6.4-py3-none-any.whl size=6122 sha256=76ac9cd012fbe1274770b29e7021edc800b2cc47a1f13690ea9fd7c9a3f8873f
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\30\38\96\2cc763113a589e09b7c3e3e9f8efe349377804de3afb46dca8
  Building wheel for progress (setup.py) ... done
  Created wheel for progress: filename=progress-1.5-py3-none-any.whl size=8073 sha256=4c069b663a796623a07bb46dbb9597935c668c17a39e54872a7eca9bc168c47d
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\4c\ff\85\0cabf2cb317421028ef98853ae5c8d84c31f3e4e11862ea977
  Building wheel for trimesh (setup.py) ... done
  Created wheel for trimesh: filename=trimesh-3.5.25-py3-none-any.whl size=452611 sha256=cd382aaab0bcd3c397e3d30e89693aa6813019e600ffd87bbbd58e709005e750
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\bd\5e\96\41a7b640b964232036bb4ddb7f4f945ebef9afafa6fb200d8c
  Building wheel for gast (setup.py) ... done
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7538 sha256=a899376fefeeed71d8a39eba8334c891e3f04847e36aca1a87e18afee8a56633
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\21\7f\02\420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
  Building wheel for PyOpenGL (setup.py) ... done
  Created wheel for PyOpenGL: filename=PyOpenGL-3.1.0-py3-none-any.whl size=1749281 sha256=9ed93c9389cf44dde1e9e5ff13e739c54798fcf2057329898477352cec267183
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\c6\83\cb\af51a0c06c33d08537b941bbfc87469e8a3c68d05f77a6a212
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4829 sha256=c2b41ff2ae98fe526b86d61d5b9b6c0b49d57d86da1dac671cec7381f4583911
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\3f\e3\ec\8a8336ff196023622fbcb36de0c5a5c218cbb24111d1d4c7f2
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.12.1-py3-none-any.whl size=19553 sha256=04ff5e0985cf60d03511e2ef0ee5356b75b207d7f2a76a6c44cd4ee21dd84173
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\62\76\4c\aa25851149f3f6d9785f6c869387ad82b3fd37582fa8147ac6
Successfully built chumpy multi-person-tracker yolov3 filterpy gdown progress trimesh gast PyOpenGL termcolor wrapt
Installing collected packages: zipp, typing-extensions, importlib-metadata, werkzeug, urllib3, python-dateutil, pyparsing, protobuf, pillow, markdown, kiwisolver, idna, h5py, grpcio, decorator, cycler, chardet, absl-py, wrapt, trimesh, tqdm, torchgeometry, termcolor, tensorflow-estimator, tensorboard, scipy, requests, PyYAML, PyWavelets, PyOpenGL, pyglet, opt-einsum, networkx, matplotlib, llvmlite, keras-preprocessing, keras-applications, imageio, google-pasta, gast, freetype-py, astor, yolov3, yacs, tensorflow, smplx, scikit-video, scikit-image, pyrender, progress, opencv-python, numba, multi-person-tracker, joblib, gdown, filterpy, chumpy
  Attempting uninstall: pillow
    Found existing installation: Pillow 8.1.2
    Uninstalling Pillow-8.1.2:
      Successfully uninstalled Pillow-8.1.2
Successfully installed PyOpenGL-3.1.0 PyWavelets-1.1.1 PyYAML-5.3.1 absl-py-0.12.0 astor-0.8.1 chardet-4.0.0 chumpy-0.70 cycler-0.10.0 decorator-4.4.2 filterpy-1.4.5 freetype-py-2.2.0 gast-0.2.2 gdown-3.6.4 google-pasta-0.2.0 grpcio-1.36.1 h5py-2.10.0 idna-2.10 imageio-2.9.0 importlib-metadata-3.7.3 joblib-0.14.1 keras-applications-1.0.8 keras-preprocessing-1.1.2 kiwisolver-1.3.1 llvmlite-0.32.1 markdown-3.3.4 matplotlib-3.1.3 multi-person-tracker-0.1 networkx-2.5 numba-0.47.0 opencv-python-4.1.2.30 opt-einsum-3.3.0 pillow-7.1.0 progress-1.5 protobuf-3.15.6 pyglet-1.5.15 pyparsing-2.4.7 pyrender-0.1.36 python-dateutil-2.8.1 requests-2.25.1 scikit-image-0.16.2 scikit-video-1.1.11 scipy-1.4.1 smplx-0.1.26 tensorboard-1.15.0 tensorflow-1.15.4 tensorflow-estimator-1.15.1 termcolor-1.1.0 torchgeometry-0.1.2 tqdm-4.28.1 trimesh-3.5.25 typing-extensions-3.7.4.3 urllib3-1.26.4 werkzeug-1.0.1 wrapt-1.12.1 yacs-0.1.6 yolov3-0.1 zipp-3.4.1

(venv_vibe) C:\MOCAP\VIBE-master>

**Comment by Tijndel** [comment]
this is only when i go until install_conda.bat. i get this when i do the prepare_data.bat part:(venv_vibe) C:\MOCAP\VIBE-master>prepare_data.bat

(venv_vibe) C:\MOCAP\VIBE-master>md data
A subdirectory or file data already exists.

(venv_vibe) C:\MOCAP\VIBE-master>cd data

(venv_vibe) C:\MOCAP\VIBE-master\data>gdown "https://drive.google.com/uc?id=1untXhYOLQtpNEy4GTY_0fL_H-k6cTf_r"
Downloading...
From: https://drive.google.com/uc?id=1untXhYOLQtpNEy4GTY_0fL_H-k6cTf_r
To: C:\MOCAP\VIBE-master\data\vibe_data.zip
561MB [01:38, 5.68MB/s]

(venv_vibe) C:\MOCAP\VIBE-master\data>cd ..

(venv_vibe) C:\MOCAP\VIBE-master>echo #### Extract the files from vibe_data ###
#### Extract the files from vibe_data ###

(venv_vibe) C:\MOCAP\VIBE-master>python unzip_vibe_data.py

(venv_vibe) C:\MOCAP\VIBE-master>copy data\vibe_data\sample_video.mp4 .
        1 file(s) copied.

(venv_vibe) C:\MOCAP\VIBE-master>echo ### creating place for torch model ###
### creating place for torch model ###

(venv_vibe) C:\MOCAP\VIBE-master>md \Users\User\.torch\models
A subdirectory or file \Users\User\.torch\models already exists.

(venv_vibe) C:\MOCAP\VIBE-master>copy data\vibe_data\yolov3.weights \Users\User\.torch\models
        1 file(s) copied.

(venv_vibe) C:\MOCAP\VIBE-master>echo ### creating place for yolo config ###
### creating place for yolo config ###

(venv_vibe) C:\MOCAP\VIBE-master>md \Users\User\.torch\config
A subdirectory or file \Users\User\.torch\config already exists.

(venv_vibe) C:\MOCAP\VIBE-master>copy yolov3.cfg \Users\User\.torch\config
        1 file(s) copied.

(venv_vibe) C:\MOCAP\VIBE-master>

**Comment by carlosedubarreto** [comment]
I didnt notice an error now.
can you run the demo?

**Comment by Tijndel** [comment]
thank you! it works now. i think i had to redownload everything.

**Comment by carlosedubarreto** [comment]
you are better than me. mine stopped working 😅

Have fun!!

**Comment by Tijndel** [comment]
thank you!
